### ISSUE TITLE
-1 in skill level doesn't work with {Skill}-{Level} pattern

### ISSUE THREAD

**Issue by wiredniko** [beaurancourt/sovereign#4]
https://github.com/beaurancourt/sovereign/blob/549613ffe35be7004bbf8e14f8ae2763ad284ac0/rules.md?plain=1#L139

I feel that the skill level shorthand doesn't work for starting skills which start at a `-1`. In your example you have  `Exert-1` or `Heal-2` .

So is it -1 in Exert, or 1 in Exert? Logically -1 would be written as `Exert--1`, vs +1 as `Exert-1`. Typographically, this is a very tiny difference, reducing readability. It's going to be even harder to read if written down on paper.

Perhaps the easiest fix would be `{Skill}:{Level}`. Now `Exert: -1` and  `Exert: 1` are much simpler to differentiate.

**Comment by beaurancourt** [comment]
I think you're totally right - I'll go through and change it to `{Skill}:{Level}`

**Comment by beaurancourt** [comment]
Updated in https://github.com/beaurancourt/sovereign/commit/ad22f9c527d8f1166d8f51ebb3e0e88b7231242d

Thanks!
